version: 0.2
env:
  variables:
    NODE_ENV: "development"
    NODE_ENV: "staging"
    NODE_ENV: "production"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - "echo Deploying in: $NODE_ENV..."
      - "echo Installing packages..."
      - "yarn install"
    finally:
      - "echo Install completed."
  build:
    commands:
      - "echo Building application..."
      - "yarn build"
    finally:
      - "echo Build completed."
      - "echo CODEBUILD_SOURCE_VERSION: $CODEBUILD_SOURCE_VERSION"
artifacts:
  base-directory: "build"
  files:
    - "**/*"
