version: 0.2
env:
  variables:
    NODE_ENV: "production"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - "echo Installing packages..."
      - "yarn install"
  build:
    commands:
      - "echo Building application..."
      - "yarn build"
  post_build:
    commands:
      - "echo Invalidating cache..."
      - "aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'"
artifacts:
  base-directory: "build"
  files:
    - "**/*"
